# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 1REI05 at PUCP (Python scripts)
author: M.Sc. Alexander Quispe Rojas
logo: figs/logo.jpg
description: Relaciones Internacionales

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution



# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 2400
  


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true



# Information about where the book exists on the web
repository:
  url: https://github.com/alexanderquispe/1REI05/tree/main # Online location of your book
  path_to_book: _build/jupyter_execute/  # Optional path to your book, relative to the repository root
  branch: main/1REI05_jb  # Which branch of the repository should be used when creating links (optional)


  
# Launch button settings
launch_buttons:
 binder             : false
 binderhub          : false
 binderhub_url      : off
 jupyterhub         : false
 thebe              : false
 colab              : false


# Launch button settings
launch_buttons:
  notebook_interface: classic #jupyterlab
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  thebe: true


# Define the name of the latex output file for PDF builds
latex:
  latex_engine                : "pdflatex"
  use_jupyterbook_latex       : true
  latex_documents:
    targetname: 1REI05_jb.tex



# Interact link settings
notebook_interface            : "notebook"



# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    html_show_copyright: false
    latex_toplevel_sectioning: 'section'
#    latex_show_urls: 'footnote'
    latex_elements.papersize: a4paper
    latex_elements.pointsize: 12pt
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

    

google_analytics:
  mytrackingcode: UA-205698170-1
  
  